#Spring Configuration
server.port=8085
spring.application.name=CustomerFeedbackApplication


#Mysql configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/customer_feedback
spring.datasource.username=root
spring.datasource.password=!123m212M@

#Mongo db credentials
MONGO_DATABASE=customer_feedback

#Spring security credentials
SPRING_SECURITY_PASSWORD=Test1234

#Jwt Secret Key
jwt.secret.key=customer_feedback_application
jwt.secret.expiration-time=3600000

#Environmental Variables
role.name=ADMIN
